function shopGuideSetup(){
	
	npc = imgNPCGuide;
	txt = "...";
	menu = ["OK"];
	menuRef = noone;
	cur = 0;
	
	switch(ww.stage){
		case 1:
			txt = "SPEND ENOUGH TIME IN THE DEPTHS, AND YOU'LL ENOUNTER A LOT OF MEN LIKE ME."; 
			txt += "\n\nIN FACT, YOU MIGHT BECOME LIKE ME!";
			txt += "\n\nJUST WALKING THE HALLS, GIVING ADVICE.";
			txt += "\n\nSPEAKING OF: WE GIVE A DIFFERENT TIP ON EVERY FLOOR, SO TRY TO TALK TO US EVERYWHERE!";
			break;
		case 2:
			txt = "A DIFFERENT TIP ON EACH FLOOR IS A LOT, HOW COULD YOU EXPECT TO REMEMBER WHICH FLOORS YOU'VE ALREADY TALKED TO US ON?"; 
			txt += "\n\nWELL, WE LIKE YOU ENOUGH TO SOLVE THAT LITTLE PROBLEM FOR FREE.";
			txt += "\n\nIF WE'RE WEARING A YELLOW SHIRT, IT'LL BE A TIP YOU'VE NEVER SEEN BEFORE.";
			break;
		case 3:
			txt = "THE BASE CHANCE TO RUN AWAY IS 25%"; 
			txt += "\n\nIF THAT SEEMS LOW, REMEMBER THAT THERE'S FOUR OF YOU. SO ON AVERAGE YOU'LL ESCAPE AFTER ABOUT A ROUND OF ATTACKS AS LONG AS EVERYONE CHOOSES RUN.";
			txt += "\n\nCOURSE, SOME CLASSES ARE BETTER AT RUNNING JUST LIKE SOME MONSTERS ARE BETTER AT CHASING.";
			break;
		case 4:
			txt = "THE FRONT PARTY MEMBER WILL RECEIVE 1/2 OF THE MELEE ATTACKS"; 
			txt += "\n\nTHE SECOND 1/4, AND 1/8 EACH FOR THE THIRD AND FOURTH";
			txt += "\n\nTHERE ARE SOME MONSTERS WITH DIFFERENT TARGETING RULES, SO PAY ATTENTION.";
			break;
	}
	
	pc.seenTip[ww.stage] = true;
	pc.guideTalk = false;
	
}